### ISSUE TITLE
Defining the Syntax Guidelines 

### ISSUE THREAD

**Issue by BrunoxD** [ET33/socket-stream-io#4]
Which one do you prefer? @ET33  @FelSiq @guilhermeht 

![Syntax](https://dl.dropboxusercontent.com/s/3apqs22c0ai8y3f/Syntax.png)

Pick one to use in the whole project.

<p><a href="https://api.gh-polls.com/poll/01CFJSP98D4NWFZMJM7NR68VSY/SYNTAX%201/vote"><img src="https://api.gh-polls.com/poll/01CFJSP98D4NWFZMJM7NR68VSY/SYNTAX%201" alt=""></a>
<a href="https://api.gh-polls.com/poll/01CFJSP98D4NWFZMJM7NR68VSY/SYNTAX%202/vote"><img src="https://api.gh-polls.com/poll/01CFJSP98D4NWFZMJM7NR68VSY/SYNTAX%202" alt=""></a></p>

**Comment by ET33** [comment]
Actually, I prefer this:

```c
printf( ANSI_COLOR_BLUE
        "Server response: "
        ANSI_COLOR_RESET
        "%s\n",
        msg.description );
```

PS.: Use space characters instead of tabs

**Comment by BrunoxD** [comment]
Right, image updated.

**Comment by BrunoxD** [comment]
It seems we have a draw, how are we gonna decide this now @ET33?

**Comment by ET33** [comment]
Well, I agree to take your approach then, as long as its consistent. I just don't want people wasting time refactoring again and again over the same thing :hankey:
