### ISSUE TITLE
Project decisions: microaudio exchanges?

### ISSUE THREAD

**Issue by FelSiq** [ET33/socket-stream-io#6]
I've created this issue to discuss with you guys about some important project decisions related to the "backbone" of the application. More precisely, I want to define how the audio exchange between server and client should work.

I've had some ideas and want to know what you guys think about it. I want to emphasize that nothing that I wrote here is defined and should not be taken as the only direction. I'd like you to try to take this into consideration and let me known if something is misleading or is a bad idea, and why.

# Microaudio concept
The main idea is to break a big audio file into _n_ much smaller files and transfer then in separated packages between server and clients.

As seen in pull request #5, I've already done a simple structure capable of processing the (already working) data exchanged between client and server. It respects the struct defined in the bib file "data-struct-def.h". In synthesis, it basically makes two assumptions:
- The "key" variable is used as a temporal reference of the package transfered between client and server. It is unknown if the packages will arrive at the correct order between client and server when the things become asynchronous and concurrent, so the "key" should be used as reference in the destiny what is the correct package order to reconstruct the audio correctly on the other side.
- It assumes that the "description" is the sound itself, in the form of bytes. These bytes will be placed in a microaudio file inside a temporary destiny subdirectory (soon i'll try to explain what I'm thinking about this) and played in the correct order.

# Temporary files
The idea behind of how the audio you be played is supported mainly on the temporary files concept. This idea support a variable number of clients for a single server.

- When a new client connects to the server, two new temporary subdirectories should be created:
1. One on the new client side, in order to keep received microaudio files from the server. 
2. One in the server side, to keep client microaudio files (independently of the purpose of these files, as it will be pointed in the next section)
![photo4963502634233341919](https://user-images.githubusercontent.com/18670260/41198747-4fea33f4-6c5b-11e8-845e-091bcca4b68c.jpg)

- While the process is running, every time the client/server wants to send a entire audio, the audio file will be broke in approximately file_size/data_unit_size microaudio file, and each one will be send just like we are already doing on the master branch. As already discussed before, each part will have a temporal ID which will be used "on the other side" to know what is the right package order.
- In the other side, each microaudio file will be kept in the temporary subdirectory, and will be played with a extern audio program in the correct order.
- When the next microaudio is played, the previous microaudio file is deleted.
![photo4963502634233341918](https://user-images.githubusercontent.com/18670260/41198746-4d2f9500-6c5b-11e8-8c0d-8f4a2912eb46.jpg)
- When the connection terminates, both temporary subdirectories will be deleted.

# Things still open to define related to this subject
- Should the server play the audio received, too? Or should it only keep the audio received by the clients and concatenate in a non-temporary file?
- What's the ideal size, in bytes, of each data unit transferred between client and server? (taking into consideration that each data unit corresponds to different system call in order to be played)

**Comment by ET33** [comment]
Really cool! Before arguing, it should be clear that I do not understand that well about media files and how they are played... but here we go. 

I think your approach might work well, but I've got some questions:
- Do we need to delete these data unit as soon as they are played? What about treat them like a cache, and keep the whole file for further usage, temporarily?
- The file to be played will be those little packages, or a file whose content is produced by appending the packages? (the point here basically is: "can I switch or modify the file on the fly?") 
- ~Will the server receive the audio file from another client, or it is a 1-server-1-client approach? (yeah, I just invented that right now :tada:)~ Hi there, just read your 1st question again

About your questions,

> - Should the server play the audio received, too? ...

IMO the server shouldn't perform media-related tasks. Only managing data passing throughout the clients.

> - What's the ideal size, in bytes, of each data unit transferred between client and server?

Given that 1500 is the MTU (_Maximum Transmission Unit_) for Ethernet protocol (which is pretty fast for audio files), maybe 1/10 of it? I will wait for other answers as well.

This might be helpful:
https://en.wikipedia.org/wiki/Maximum_transmission_unit#MTUs_for_common_media
https://tools.ietf.org/html/rfc879 (Back in **1983**)

**Comment by BrunoxD** [comment]
I agree with the questions pointed out by @ET33.

I don't think the server should receive files from the clients, it may cause a breach of security and we have to implement dedicate interface to deal with.

One point I couldn't miss, how are we gonna check if the file is an audio file, by extension or trying to play and deal with the errors?

About the MTU, I really have no idea of the size we should use. I believe it's more interesting to test empirically to see if there is much difference.

Can you explain better the purpose of the temp folder to each connected client on the server? Is this really necessary?

**Comment by FelSiq** [comment]
@ET33 questions and points:
> Do we need to delete these data unit as soon as they are played? What about treat them like a cache, and keep the whole file for further usage, temporarily?

That depends of what kind of audio we are streaming. If we are using a perspective Spotify/Youtube like, where the clients may want to repeat the same audio, then its worth to keep then. If we're adopting a Hangouts/Skype-like perspective (real time communication), then I don't think the cache is relevant.  

> The file to be played will be those little packages, or a file whose content is produced by appending the packages? (the point here basically is: "can I switch or modify the file on the fly?")

I was assuming that each package will be played separately, as each one has nothing to do with the previous ones. The trick is to play then in the correct order. At first, I was thinking to not create a pseudo-permanent file that concatenates every data unit but, again, that will depends mainly of what  audio streaming flavor we're adopting.

@BrunoxD questions and points:
> I don't think the server should receive files from the clients, it may cause a breach of security and we have to implement dedicate interface to deal with.

So the application will not support data transfer between clients, I suppose? I've understood that @ET33 seems to have another idea about it ("IMO the server shouldn't perform media-related tasks. Only managing data passing throughout the clients.") when he says "throughout". Should we discuss deeper about this?

> Can you explain better the purpose of the temp folder to each connected client on the server? Is this really necessary?

Yes. At first, I was supposing that exists data exchange from both sides (Client and Server). This data is in the form of little packages and they must be place somewhere in the destiny separated from the local data to avoid inconsistencies. This is where the temp folders comes in.

> One point I couldn't miss, how are we gonna check if the file is an audio file, by extension or trying to play and deal with the errors?

I think we can't do it In a consistent manner without knowing how exactly each type of audio file is build inside in the binary form in order to check in the lowest level possible. I think the extension thing is not worth the work, as someone always can manually change the extension of any file to any valid audio type file and still transfer the data normally.

**Comment by BrunoxD** [comment]
> That depends of what kind of audio we are streaming. If we are using a perspective Spotify/Youtube like, where the clients may want to repeat the same audio, then its worth to keep then. If we're adopting a Hangouts/Skype-like perspective (real time communication), then I don't think the cache is relevant.

I think for the operations in the MVP, cache is no needed, let's simplify for now and first make the program receive the audio packages and play them in the right order through the socket.

> So the application will not support data transfer between clients, I suppose? I've understood that @ET33 seems to have another idea about it ("IMO the server shouldn't perform media-related tasks. Only managing data passing throughout the clients.") when he says "throughout". Should we discuss deeper about this?

Between clients? I need a clarification here, what are the operations that could demand this? In my perspective, the client only would communicate with the server and could do operations like list musics, play, stop and exit. The server would provide an interface to properly respond to each client connected to him.

**Comment by ET33** [comment]
> That depends of what kind of audio we are streaming. If we are using a perspective Spotify/Youtube like, where the clients may want to repeat the same audio, then its worth to keep then. If we're adopting a Hangouts/Skype-like perspective (real time communication), then I don't think the cache is relevant.

Good point, I didn't considerate Skype like applications when writing this.

About the word "cache", I was referring to 'not delete the file immediately' and keep it for further usages (e.g. play audio again), nothing exceptional.

>I don't think the server should receive files from the clients, it may cause a breach of security and we have to implement dedicate interface to deal with.

If we are taking the MVP approach, I don't think that would be an issue.

> Between clients? 

Yeah, when discussing with @FelSiq in person, we agreed that it would be a communication between clients. Allowing clients to upload their files to the server and then to the other client sounds fun to me :D
